workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fashion-amigo.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Create entitlements file
        script: |
          cat > ios/App/App.entitlements <<EOF
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
           <plist version="1.0">
              <dict>
                 <key>com.apple.developer.associated-domains</key>
                   <array>
                     <string>applinks:fashionamigo.app</string>
                   </array>
              </dict>
           </plist>
     - name: Fix CocoaPods script phases
       script: |
         ruby -e "
         require 'xcodeproj'
         project_path = 'ios/App/App.xcodeproj'
         project = Xcodeproj::Project.open(project_path)
    
         project.targets.each do |target|
         target.shell_script_build_phases.each do |phase|
          if phase.name && phase.name.include?('[CP]')
            phase.always_out_of_date = true
          end
         end
        end
    
    project.save
      - name: Disable script phase warnings
        script: |
          sed -i '' 's/ENABLE_USER_SCRIPT_SANDBOXING = YES/ENABLE_USER_SCRIPT_SANDBOXING = NO/g' ios/App/App.xcodeproj/project.pbxproj
      - name: Set up code signing
        script: |
           xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
