workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fashion-amigo.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        DISABLE_COCOAPODS_SCRIPT_WARNINGS: "YES"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install Pods
        script: |
          cd ios/App
          pod install --repo-update
      - name: Set up code signing
        script: |
           xcode-project use-profiles
      - name: Build iOS app
        script: |
          sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d' ios/App/App.xcodeproj/project.pbxproj
          xcodebuild archive \
          -workspace ios/App/App.xcworkspace \
          -scheme App \
          -configuration Release \
          -archivePath $CM_BUILD_DIR/build/App.xcarchive \
           CODE_SIGN_STYLE=Manual \
          PROVISIONING_PROFILE_SPECIFIER=FashionAmigoIosProvisioningProfile \
          DEVELOPMENT_TEAM=MGLWBWDJWL \
          GCC_TREAT_WARNINGS_AS_ERRORS=NO \
          RUN_CLANG_STATIC_ANALYZER=NO
    
          xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/build/App.xcarchive \
          -exportPath $CM_BUILD_DIR/build \
          -exportOptionsPlist ios/App/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
