workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fashion-amigo.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        DISABLE_COCOAPODS_SCRIPT_WARNINGS: "YES"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Fix CocoaPods script phases
        script: |
        # Add output files to CocoaPods script phases
        cat > fix_pods.rb << 'EOF'
        require 'xcodeproj'
        project = Xcodeproj::Project.open('ios/App/App.xcodeproj')
        project.targets.each do |target|
          target.shell_script_build_phases.each do |phase|
            if phase.name && phase.name.start_with?('[CP]')
               phase.output_paths = ['$(DERIVED_FILE_DIR)/Pods-dummy-output.txt'] if phase.output_paths.empty?
            end
          end
        end
        project.save
        EOF
        ruby fix_pods.rb
      - name: Set up code signing
        script: |
           xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App 
    artifacts:
      - build/ios/ipa/*.ipa
