workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      cocoapods: default
    scripts:
     - name: Install dependencies
       script: |
         npm ci
     - name: Sync Capacitor
       script: |
         node node_modules/@capacitor/cli/bin/capacitor sync ios
     - name: Set up code signing
       script: |
        keychain initialize
     - name: Build iOS app
       script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --export-options-plist $CM_BUILD_DIR/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY_IDENTIFIER
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
