workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fashion-amigo.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        DISABLE_COCOAPODS_SCRIPT_WARNINGS: "YES"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install Pods
        script: |
          cd ios/App
          pod install --repo-update
      - name: Set up code signing
        script: |
           xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App 
    artifacts:
      - build/ios/ipa/*.ipa
