workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fashion-amigo.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        DISABLE_COCOAPODS_SCRIPT_WARNINGS: "YES"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Fix CocoaPods outputs
        script: |
          sed -i '' 's/shellScript = "\\${PODS_ROOT}\\/Target Support Files\\/Pods-App\\/Pods-App-frameworks.sh\\n";/shellScript = "\\${PODS_ROOT}\\/Target Support Files\\/Pods-App\\/Pods-App-frameworks.sh\\n";\n\t\t\toutputPaths = (\n\t\t\t\t"\$(DERIVED_FILE_DIR)\/Pods-App-frameworks.txt",\n\t\t\t);/g' ios/App/App.xcodeproj/project.pbxproj
      - name: Set up code signing
        script: |
           xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --archive-flags="GCC_TREAT_WARNINGS_AS_ERRORS=NO"
    artifacts:
      - build/ios/ipa/*.ipa
