workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
    ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fashionamigo.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Disable script phase warnings
        script: |
          sed -i '' 's/ENABLE_USER_SCRIPT_SANDBOXING = YES/ENABLE_USER_SCRIPT_SANDBOXING = NO/g' ios/App/App.xcodeproj/project.pbxproj
      - name: Set up code signing
        script: |
           xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
